// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWcVDGKFMUppGH7ALB-MQhM5IxDIKKveM',
    appId: '1:374435470644:ios:098c1059ee062821249961',
    messagingSenderId: '374435470644',
    projectId: 'global-luxury-escapes',
    storageBucket: 'global-luxury-escapes.appspot.com',
    iosBundleId: 'com.example.globalLuxuryEscapes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWcVDGKFMUppGH7ALB-MQhM5IxDIKKveM',
    appId: '1:374435470644:ios:098c1059ee062821249961',
    messagingSenderId: '374435470644',
    projectId: 'global-luxury-escapes',
    storageBucket: 'global-luxury-escapes.appspot.com',
    iosBundleId: 'com.example.globalLuxuryEscapes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4btZjWfNLcvElal7LW0cUKYQ-H_Mp654',
    appId: '1:374435470644:web:92b7b24b47de1502249961',
    messagingSenderId: '374435470644',
    projectId: 'global-luxury-escapes',
    authDomain: 'global-luxury-escapes.firebaseapp.com',
    storageBucket: 'global-luxury-escapes.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4btZjWfNLcvElal7LW0cUKYQ-H_Mp654',
    appId: '1:374435470644:web:92b7b24b47de1502249961',
    messagingSenderId: '374435470644',
    projectId: 'global-luxury-escapes',
    authDomain: 'global-luxury-escapes.firebaseapp.com',
    storageBucket: 'global-luxury-escapes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgoZxnWS212AVnbh7XxVWWYJ8RrpyaI0w',
    appId: '1:374435470644:android:c3c5d757a7397e03249961',
    messagingSenderId: '374435470644',
    projectId: 'global-luxury-escapes',
    storageBucket: 'global-luxury-escapes.appspot.com',
  );

}